### ISSUE TITLE
The dotted field 'Price Min.' in 'messages.Price Min.' is not valid for storage.

### ISSUE THREAD

**Issue by kudzuu** [yiisoft/yii2-mongodb#158] opened 2016-10-18 08:32 UTC
### What steps will reproduce the problem?

Setup same as in docs. 
Call Yii::t('app', 'Price Min.');
### What do you get instead?

MongoDB Exception – yii\mongodb\Exception
The dotted field 'Price Min.' in 'messages.Price Min.' is not valid for storage.
↵
Caused by: MongoDB\Driver\Exception\BulkWriteException
The dotted field 'Price Min.' in 'messages.Price Min.' is not valid for storage.

in /var/www/vendor/yiisoft/yii2-mongodb/Command.php at line 241
### Additional info

| Q | A |
| --- | --- |
| Yii version |  |
| Yii MongoDB version |  |
| MongoDB server version |  |
| PHP version |  |
| Operating system |  |

**Comment by klimov-paul** [comment] 2016-10-18 08:42
Unable to reproduce saving keys with dot (`.`) working fine for i18n collection.
There is a unit test, which proves this:
https://github.com/yiisoft/yii2-mongodb/blob/master/tests/i18n/MongoDbMessageSourceTest.php#L38-L78

**Comment by klimov-paul** [comment] 2017-11-01 13:41
Reproduced.
It seems the behavior varies depending on driver version.

**Comment by klimov-paul** [comment] 2017-11-01 14:47
Resolved by commit 26c9d24

**Closed** 2017-11-01 14:46 UTC
Labels: type:bug
