### ISSUE TITLE
New MongoDB driver

### ISSUE THREAD

**Issue by tuyakhov** [yiisoft/yii2-mongodb#56] opened 2015-10-20 08:08 UTC
Hi guys.
Are you planning in the near future migrate to new [MongoDB driver for PHP](http://docs.php.net/manual/en/set.mongodb.php). As mentioned [here](https://www.mongodb.com/blog/post/call-feedback-new-php-and-hhvm-drivers) next-generation driver will support PHP 5.x, HHVM, and PHP 7.0. Since new PHP release is very close, some of us would be happy to have ability to use MongoDB with new 7.0 version or HHVM as well.

Thanks

**Comment by sokrat** [comment] 2015-12-01 06:54
+1
```
# pecl install mongo  
WARNING: "pecl/mongo" is deprecated in favor of "channel:///mongodb"
```

**Comment by webspec2012** [comment] 2015-12-05 09:41
+1, required for php 7...

**Comment by o-rey** [comment] 2015-12-09 15:43
+1

**Comment by miradnan** [comment] 2015-12-09 21:27
+1

**Comment by LAV45** [comment] 2015-12-13 22:51
https://github.com/mongodb/mongo-php-driver/tree/PHP7

**Comment by hardsetting** [comment] 2015-12-14 03:31
+1

**Comment by gallexme** [comment] 2015-12-15 23:09
+1 cant wait

**Comment by gallexme** [comment] 2015-12-18 20:28
Im Currently working on a HHVM/PHP7 Compatible Version
what works for now: is Saving Data
with reading i got the Problem that the new Cursor is not working much like the old one(can only be iterated once and only allows to get all results once), so i think that making a version compatible to New Mongo Connector and old Connector wont work

**Comment by hardsetting** [comment] 2015-12-19 20:47
@gallexme I'm been working to a version that uses the newest driver too.
Currently it passes:
* ActiveDataProviderTest
* ActiveRecordTest
* ActiveRelationTest
* CacheTest
* CollectionTest

I can't see any commits from your repo, I'd like to see it to know if I should stop working at my version :)

**Comment by gallexme** [comment] 2015-12-19 21:35
@hardsetting check https://github.com/TheManagers/yii2-mongodb

**Comment by nguago** [comment] 2015-12-25 05:15
+1

**Comment by bobolone7** [comment] 2015-12-27 18:08
@gallexme Hello please could I try your version?

**Comment by gallexme** [comment] 2015-12-27 18:29
@bobolone7 
try it
require": {
"themanagers/yii2-mongodb": "dev-hhvm-version",
themanagers/yii2-mongodb-hhvm": "dev-master",
"mongodb/mongodb": "^0.2.0"
}

**Comment by bobolone7** [comment] 2015-12-27 18:39
@gallexme Thank you, should I always use:
        'mongodb' => [
            'class' => '\yii\mongodb\Connection',
            'dsn' => 'mongodb://username:password@localhost:27017/dbnamel',
        ],

?
Because I'm getting this error:
Declaration of MongoClient::selectCollection($db, $collection) should be compatible with MongoDB\Client::selectCollection($databaseName, $collectionName, MongoDB\Driver\WriteConcern $writeConcern = NULL, MongoDB\Driver\ReadPreference $readPreference = NULL)

**Comment by gallexme** [comment] 2015-12-27 18:41
ah strict php
sorry u can just add those missing parameters to the selectCollection function

**Comment by bobolone7** [comment] 2015-12-27 19:04
@gallexme I'm sorry but I can't get it work... You refer to the selectCollection function in your MongoClient.php ?

**Comment by nigelterry** [comment] 2016-01-10 03:37
+1 Need for PHP7 testing. Failed to get @gallexme version working

**Comment by bobolone7** [comment] 2016-01-10 12:18
@nigelterry same problem for me, I'm using mongofill to use yii2-mongodb 2.0.4 on php7
{
    "require": {
        "mongofill/mongofill": "dev-master"
    }
}

**Comment by hardsetting** [comment] 2016-01-12 10:35
@bobolone7 cool fix! Didn't know mongofill!

@all if you don't need GridFS functionalities you could try out my version:
https://github.com/hardsetting/yii2-mongodb
It passes all tests except GridFS ones.

**Comment by sunbay** [comment] 2016-01-15 09:53
+1 
Please update !

**Comment by sunbay** [comment] 2016-01-15 11:38
https://github.com/hardsetting/yii2-mongodb
It's not work in PHP7. 
class MongoDB/Client not found

**Comment by hardsetting** [comment] 2016-01-15 12:06
@sunbay
It's a missing Composer dependency, you can fix it by adding
* "mongodb/mongodb": ">=1.0.0@beta"

to your composer.json

**Alternatively**, I've created a the package of my fork on packagist, so you can simply replace yiisoft/yii2-mongodb with
* "hardsetting/yii2-mongodb": "*@dev"

**Comment by LAV45** [comment] 2016-01-15 14:52
@hardsetting

**Comment by hardsetting** [comment] 2016-01-15 15:21
@LAV45 in my fork I used the official PHP library (https://github.com/mongodb/mongo-php-library) made from the same developers that are working on the new mongodb driver.
The missing class is from that library.

If you have copied the source of my fork in your project you must include the dependency in your composer.json by the command:
composer require "mongodb/mongodb: >=1.0.0@beta" --prefer-dist

Alternatively, you can simply replace "yiisoft/yii2-mongodb": "*" with "hardsetting/yii2-mongodb": "*" so you will be using my fork instead of the official repo, and the required dependencies will be resolved by composer.

**Comment by nigelterry** [comment] 2016-01-18 03:38
@bobolone7 -Thanks. mongofill works like a dream :-)

**Comment by sunbay** [comment] 2016-01-24 08:10
@hardsetting Thanks! It's working.

**Comment by Olegf13** [comment] 2016-02-12 10:14
+1 for new driver usage

**Comment by deplop** [comment] 2016-03-02 16:44
@hardsetting 
I am using your mongodb version with 90,000 documents in my Post collection.
And I find out that either Post::find()->count() or Post::find()->where([])->count() takes more than 20 seconds to execute. 
1 12:04:38.380 0.6 ms yii\mongodb\Connection::open Opening MongoDB connection: mongodb://mongodb:27017/vjc
2 12:04:38.386 18402.4 ms yii\mongodb\Query::count find.count(null)
3 12:04:56.790 44.4 ms yii\mongodb\Query::fetchRows find({})
4 12:04:56.841 0.0 ms yii\mongodb\Query::fetchRows find({})
5 12:04:56.842 0.0 ms yii\mongodb\Query::fetchRows find({})
6 12:04:56.843 0.0 ms yii\mongodb\Query::fetchRows find({})
7 12:04:56.844 0.0 ms yii\mongodb\Query::fetchRows find({})
8 12:04:56.845 0.0 ms yii\mongodb\Query::fetchRows find({})
9 12:04:56.846 0.0 ms yii\mongodb\Query::fetchRows find({})
10 12:04:56.847 0.0 ms yii\mongodb\Query::fetchRows find({})
11 12:04:56.848 0.0 ms yii\mongodb\Query::fetchRows find({})
12 12:04:56.849 0.0 ms yii\mongodb\Query::fetchRows find({})
13 12:04:56.850 0.0 ms yii\mongodb\Query::fetchRows find({})
14 12:04:56.851 0.0 ms yii\mongodb\Query::fetchRows find({})
15 12:04:56.852 0.0 ms yii\mongodb\Query::fetchRows find({})
16 12:04:56.853 0.0 ms yii\mongodb\Query::fetchRows find({})
17 12:04:56.854 0.0 ms yii\mongodb\Query::fetchRows find({})
18 12:04:56.855 0.0 ms yii\mongodb\Query::fetchRows find({})
19 12:04:56.856 0.0 ms yii\mongodb\Query::fetchRows find({})
20 12:04:56.857 0.0 ms yii\mongodb\Query::fetchRows find({})

Am I getting something wrong?

**Comment by SilverFire** [comment] 2016-03-03 06:18
@deplop I've asked you to try debugging in your issue https://github.com/yiisoft/yii2-mongodb/issues/84#issuecomment-188403290. Did you do it?

P.S.: Issues mixing brings nothing except mess. Answer in your issue, please.

**Comment by deplop** [comment] 2016-03-03 13:20
@SilverFire 
I think I have figured out the problem. The problem is I was using PHP7 so I switched to hardsetting/yii2-mongodb for compatible with the new php mongodb driver, but I didn't remember that. This morning I installed mongofill for HHVM and switched back to yiisoft/yii2-mongodb and there is no longer bug. So I guess it's hardsetting's bug. I have reported it to him. 

You can now close this. Thanks

**Comment by SilverFire** [comment] 2016-03-04 12:17
Could you give a link

> I have reported it to him.

Could you give a link to that report, please?

**Comment by conghai** [comment] 2016-03-24 04:17
For now, not have any solutions for PHP7 mongo driver, it's right ?

**Comment by tuyakhov** [comment] 2016-03-24 08:52
There are few temporary solutions for now. You can use mongofill instead of native php implemetation of mongodb driver. Or you can use one of the forks of yii2-mongodb extension. For example mine: https://github.com/tuyakhov/yii2-mongodb or one that @hardsetting mentioned before.
You can do it by adding to your composer.json something like:
```
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/tuyakhov/yii2-mongodb"
    }
  ],
  "require": {
    "yiisoft/yii2-mongodb": "dev-mongodb",
    "mongodb/mongodb": "dev-master",
  }
```
But GridFS will be missing because it is not fully implemented yet in `mongo-php-library`. https://github.com/alcaeus/mongo-php-adapter/issues/82

**Comment by sharaf84** [comment] 2016-03-24 13:34
@hardsetting 

I tried that

```
$collection = Yii::$app->mongodb->getCollection('users');
$collection->insert(['name' => 'Sharaf', 'age' => 40]);
```
and got 

MongoDB Exception – yii\mongodb\Exception
Authentication failed.
↵
Caused by: MongoDB\Driver\Exception\AuthenticationException
Authentication failed.

in /../vendor/mongodb/mongodb/src/Operation/InsertOne.php at line 86

**Comment by andreyshade** [comment] 2016-04-19 14:52
@sharaf84 
Try this in config 
`'dsn' => 'mongodb://localhost:27017/your_database',`

**Comment by serieznyi** [comment] 2016-04-29 20:06
@tuyakhov 

https://github.com/tuyakhov/yii2-mongodb/blob/mongodb/Query.php#L290

I think this may be a problem. I tray yours fork and get a problem. If collection contains a very big count of documents (in my case this is been from 20000 to 200000), then you will not have enough memory for this operation.

**Comment by Sammaye** [comment] 2016-05-14 22:19
Turns out I was able to get a lapse in my work load over the weekend and got this ext working here https://github.com/Sammaye/yii2-mongodb.

I have not got the tests working but I have an application, a comic aggregater, working fully 100%.

I can make a PR if you like so you can see the differences?

I have only really rewritten the connection.php class to allow for a slightly different config setup but the old setup still works and the key parts of it's API have not changed

**Comment by samdark** [comment] 2016-05-14 23:01
@Sammaye yes, would be handy.

**Comment by miradnan** [comment] 2016-05-26 13:04
@hardsetting How do I install your fork? I have added the below lines to composer, but it doesn't work.

<pre>
"mongodb/mongodb": ">=1.0.0@beta",
"hardsetting/yii2-mongodb": "*@dev"
</pre>

<pre>
Problem 1
    - hardsetting/yii2-mongodb 2.0.x-dev requires yiisoft/yii2 >=2.0.x-dev -> satisfiable by yiisoft/yii2[dev-master, 2.0.x-dev] but these conflict with your requirements or minimum-stability.
    - hardsetting/yii2-mongodb dev-master requires yiisoft/yii2 >=2.0.x-dev -> satisfiable by yiisoft/yii2[dev-master, 2.0.x-dev] but these conflict with your requirements or minimum-stability.
    - hardsetting/yii2-mongodb dev-56-new-mongodb-driver requires yiisoft/yii2 >=2.0.x-dev -> satisfiable by yiisoft/yii2[dev-master, 2.0.x-dev] but these conflict with your requirements or minimum-stability.
    - hardsetting/yii2-mongodb 2.0.6 requires yiisoft/yii2 >=2.0.x-dev -> satisfiable by yiisoft/yii2[dev-master, 2.0.x-dev] but these conflict with your requirements or minimum-stability.
    - hardsetting/yii2-mongodb 2.0.5 requires ext-mongo >=1.5.0 -> the requested PHP extension mongo is missing from your system.
    - hardsetting/yii2-mongodb 2.0.4 requires ext-mongo >=1.5.0 -> the requested PHP extension mongo is missing from your system.
    - hardsetting/yii2-mongodb 2.0.3 requires ext-mongo >=1.5.0 -> the requested PHP extension mongo is missing from your system.
    - hardsetting/yii2-mongodb 2.0.2 requires ext-mongo >=1.5.0 -> the requested PHP extension mongo is missing from your system.
    - hardsetting/yii2-mongodb 2.0.1 requires ext-mongo >=1.4.0 -> the requested PHP extension mongo is missing from your system.
    - hardsetting/yii2-mongodb 2.0.0-rc requires ext-mongo >=1.3.0 -> the requested PHP extension mongo is missing from your system.
    - hardsetting/yii2-mongodb 2.0.0-beta requires ext-mongo >=1.3.0 -> the requested PHP extension mongo is missing from your system.
    - hardsetting/yii2-mongodb 2.0.0 requires ext-mongo >=1.3.0 -> the requested PHP extension mongo is missing from your system.
    - Installation request for hardsetting/yii2-mongodb *@dev -> satisfiable by hardsetting/yii2-mongodb[2.0.0, 2.0.0-beta, 2.0.0-rc, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, dev-56-new-mongodb-driver, dev-master, 2.0.x-dev].
</pre>

**Comment by indicalabs** [comment] 2016-05-29 15:55
@Sammaye I tried to use your mognodb extension with PHP7,
But I am getting the below error
<code> PHP Compile Error – yii\base\ErrorException
Cannot declare class yii\mongodb\Database because the name is already in use</code>

<code> in /var/www/html/vendor/sammaye/yii2-mongodb/Database.php at line 26 </code>

any inputs much appreciated please

**Comment by Sammaye** [comment] 2016-05-29 19:14
Fascinating that is a bug and I wonder why it doesn't arise on my PHP7 install.

Man, I do hate PHP7 at times, it is so unpredictable

**Comment by Sammaye** [comment] 2016-05-29 19:15
Okay fixed, try again

**Comment by klimov-paul** [comment] 2016-06-08 14:34
Implementation:
https://github.com/yiisoft/yii2-mongodb/pull/116

**Closed** 2016-06-09 07:46 UTC
Labels: enhancement

**Comment by klimov-paul** [comment] 2016-06-09 07:48
Resolved by #116

**Comment by AlexJapson** [comment] 2016-07-08 11:41
##### Hi guys, i have a problem.
I can't connect to mongodb from yii2 
![image](https://cloud.githubusercontent.com/assets/5379312/16686244/44e5137a-452a-11e6-8623-2c3f01b7d136.png)

in web.php 
``` php
'mongodb' => [
            'class' => '\yii\mongodb\Connection',
            'dsn' => 'mongodb://localhost:27017/admin',
        ],
```
How i can fix it?

**Comment by cebe** [comment] 2016-07-08 11:42
please open a new issue for this.

**Comment by conghai** [comment] 2016-07-09 01:54
@cebe This issue was fixed in version 2.5.x and 3.x

Please check.

**Comment by asalem** [comment] 2016-12-05 12:10
if it's already installed checkout composer update --ignore-platform-reqs

**Comment by elzix** [comment] 2018-01-25 09:11
I just tried
```
require": {
"themanagers/yii2-mongodb": "dev-hhvm-version",
"themanagers/yii2-mongodb-hhvm": "dev-master",
"mongodb/mongodb": "^0.2.0"
}
```
and used `composer update --ignore-platform-reqs` and got error
`Declaration of MongoClient::selectCollection($db, $collection) should be compatible with MongoDB\Client::selectCollection($databaseName, $collectionName, ?MongoDB\Driver\WriteConcern...`

I then tried
```
require": {
"themanagers/yii2-mongodb": "dev-hhvm-version",
"mongofill/mongofill": "dev-master",
"mongodb/mongodb": "^0.2.0"
}
```
and used `composer update --ignore-platform-reqs` and now I get error 
`The file or directory to be published does not exist: ...../vendor/bower-asset/jquery/dist`

Which means mongodb is no longer the problem.
However `--ignore-platform-reqs` is causing new problems.

Is Yii2 + mongodb stable with PHP7 or should I revert to PHP5?
For the new error, I have tried everything in [this post](https://stackoverflow.com/questions/34402608/yii2-fresh-install-vendor-bower-jquery-dist-path-is-wrong) but the error persists. Any suggestions?

**Comment by elzix** [comment] 2018-01-25 10:57
Adding the config
```
"asset-installer-paths": {
  "bower-asset-library": "vendor/bower-asset"
}
```
solved the bower issue. 

An error did appear at the bottom of my page
```
Exception (MongoDB Exception) 'yii\mongodb\Exception' with message 'unrecognized write concern field: multiple' in /.../vendor/yiisoft/yii2-mongodb/Collection.php:453 Stack trace: #0 /.../vendor/yiisoft/yii2-mongodb/Session.php(147): yii\mongodb\Collection->update(Array, Array, Array)
```
That was not there with PHP5. I'll just use `web\CacheSession` instead. I just hope I don't run into some major db related errors. I do hope a stable release becomes available.

**Comment by elzix** [comment] 2018-01-25 12:04
I have been using `"yiisoft/yii2-mongodb": "~2.0.0"` for PHP5.
I did not realize changing to `"yiisoft/yii2-mongodb": "~2.1.0"` would allow it to work with PHP7.
Thanks for the fix.

**Comment by miradnan** [comment] 2018-01-25 14:51
PHP 5 uses mongo client and PHP 7 doesn’t support that. It uses another mongodb driver.

I cloned the yii2 mongo library and made required changes to support new PHP 7 mongodb driver. Below is my repo link.

https://github.com/miradnan/yii2-mongodb

Feel free to use and make updates.

Here is nice answer on stackoverflow
https://stackoverflow.com/questions/34486808/installing-the-php-7-mongodb-client-driver


Best Regards,

Mir Adnan

**Comment by nalex-macaroni** [comment] 2018-02-03 04:06
New here - boy mongo on PHP7 is an effing mess. I've blown two days trying to get back to where I was two years ago. Jeez.
