### ISSUE TITLE
 'The view file does not exist: '

### ISSUE THREAD

**Issue by kudzuu** [yiisoft/yii2-mongodb#96] opened 2016-04-04 08:47 UTC
### What steps will reproduce the problem?
```
yii2-advanced

./yii mongodb-migrate/create create_users_collection
```

### What's expected?
Migration in console/migrations

### What do you get instead?

```
`Create new migration '/var/www/console/migrations/m160404_084614_create_users_collection.php'? (yes|no) [no]:y
Exception 'yii\base\InvalidParamException' with message 'The view file does not exist: '

in /var/www/vendor/yiisoft/yii2/base/View.php:226

Stack trace:
#0 /var/www/vendor/yiisoft/yii2/base/Controller.php(420): yii\base\View->renderFile(NULL, Array, Object(yii\mongodb\console\controllers\MigrateController))
#1 /var/www/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(531): yii\base\Controller->renderFile(NULL, Array)
#2 [internal function]: yii\console\controllers\BaseMigrateController->actionCreate('create_users_co...')
#3 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#4 /var/www/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#5 /var/www/vendor/yiisoft/yii2/console/Controller.php(108): yii\base\Controller->runAction('create', Array)
#6 /var/www/vendor/yiisoft/yii2/base/Module.php(454): yii\console\Controller->runAction('create', Array)
#7 /var/www/vendor/yiisoft/yii2/console/Application.php(167): yii\base\Module->runAction('mongodb-migrate...', Array)
#8 /var/www/vendor/yiisoft/yii2/console/Application.php(143): yii\console\Application->runAction('mongodb-migrate...', Array)
#9 /var/www/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#10 /var/www/yii(27): yii\base\Application->run()
#11 {main}
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2
| PHP version      |
| Operating system |

**Comment by SilverFire** [comment] 2016-04-04 09:50
> `#1 /var/www/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(531): yii\base\Controller->renderFile(NULL, Array)`

Null is passed to renderFile. 

What is inside `create_users_collection` migration?

**Comment by kudzuu** [comment] 2016-04-04 09:56
I'm trying to create new migration, create_users_collection file doesn't exists yet.

**Comment by klimov-paul** [comment] 2016-04-05 11:02
This is caused by recent changes at `BaseMigrateController`, which was intended to support migration autogenerating:
https://github.com/yiisoft/yii2/commit/9afd240ab6e4f6b51d274e413b7879cae452c590#diff-98cca1462018f263e0366c3b572bea3b

I suppose, this should be fixed at the `yii2` repo.

**Comment by kudzuu** [comment] 2016-04-05 12:30
Спасибо за поиски! Фикс доступен?

**Comment by klimov-paul** [comment] 2016-04-05 12:42
You may use lesser version of the `yii2` package: `<=2.0.7` along with the master code of this repository.

**Comment by kudzuu** [comment] 2016-04-05 13:10
Some fixes from 2.0.7 relaying on my application.

**Comment by klimov-paul** [comment] 2016-04-05 15:02
https://github.com/yiisoft/yii2/issues/11280

**Closed** 2016-04-05 20:06 UTC
Labels: bug

**Comment by miholeus** [comment] 2017-08-02 15:38
Yii 2.0.12
```
Exception 'yii\base\ViewNotFoundException' with message 'The view file does not exist: /app/vendor/yiisoft/yii2/mongodb/views/migration.php'
```
