### ISSUE TITLE
indexBy stop working

### ISSUE THREAD

**Issue by mpazaran** [yiisoft/yii2-mongodb#252] opened 2018-03-07 18:37 UTC
### What steps will reproduce the problem?
Try to use indexBy method
$all = $query
            ->indexBy('field')
            ->all()
### What's expected?
The result or query must be and assoc using the indexBy property
$all = [
 'field_value_1' => Model...
 'field_value_2' => Model...
 'field_value_3' => Model...
]
### What do you get instead?
A flat array
$all = [
0 => Model...
1 => Model...
2 => Model...
]

### Additional info

| Q                      | A
| ---------------------- | ---
| Yii version            | 2.0.14
| Yii MongoDB version    | ~2.1.0
| MongoDB server version | 3.6.2
| PHP version            | 7.2.2
| Operating system       | Ubuntu 16.0.2

**Comment by rustamwin** [comment] 2018-03-07 18:45
#251

**Comment by samdark** [comment] 2018-03-07 18:58
Duplicate of #251

**Closed** 2018-03-07 18:58 UTC
