### ISSUE TITLE
It takes 20 seconds for count

### ISSUE THREAD

**Issue by deplop** [yiisoft/yii2-mongodb#84] opened 2016-02-23 15:30 UTC
I have 90,000 documents in my Post collection.

And I find out that either Post::find()->count() or Post::find()->where([])->count() takes more than 20 seconds to execute. 
Am I getting something wrong?

**Comment by SilverFire** [comment] 2016-02-23 16:38
Maybe related to #82

How long it takes to execute query directly to the mongo console?

**Comment by deplop** [comment] 2016-02-24 00:31
It returns immediately in mongo console.

**Comment by SilverFire** [comment] 2016-02-24 06:08
Could you show the query, generated by Yii? Other queries are fast?

**Comment by deplop** [comment] 2016-02-24 12:05
Here it is 
1	12:04:38.380	0.6 ms	yii\mongodb\Connection::open	Opening MongoDB connection: mongodb://mongodb:27017/vjc
2	12:04:38.386	18402.4 ms	yii\mongodb\Query::count	find.count(null)
3	12:04:56.790	44.4 ms	yii\mongodb\Query::fetchRows	find({})
4	12:04:56.841	0.0 ms	yii\mongodb\Query::fetchRows	find({})
5	12:04:56.842	0.0 ms	yii\mongodb\Query::fetchRows	find({})
6	12:04:56.843	0.0 ms	yii\mongodb\Query::fetchRows	find({})
7	12:04:56.844	0.0 ms	yii\mongodb\Query::fetchRows	find({})
8	12:04:56.845	0.0 ms	yii\mongodb\Query::fetchRows	find({})
9	12:04:56.846	0.0 ms	yii\mongodb\Query::fetchRows	find({})
10	12:04:56.847	0.0 ms	yii\mongodb\Query::fetchRows	find({})
11	12:04:56.848	0.0 ms	yii\mongodb\Query::fetchRows	find({})
12	12:04:56.849	0.0 ms	yii\mongodb\Query::fetchRows	find({})
13	12:04:56.850	0.0 ms	yii\mongodb\Query::fetchRows	find({})
14	12:04:56.851	0.0 ms	yii\mongodb\Query::fetchRows	find({})
15	12:04:56.852	0.0 ms	yii\mongodb\Query::fetchRows	find({})
16	12:04:56.853	0.0 ms	yii\mongodb\Query::fetchRows	find({})
17	12:04:56.854	0.0 ms	yii\mongodb\Query::fetchRows	find({})
18	12:04:56.855	0.0 ms	yii\mongodb\Query::fetchRows	find({})
19	12:04:56.856	0.0 ms	yii\mongodb\Query::fetchRows	find({})
20	12:04:56.857	0.0 ms	yii\mongodb\Query::fetchRows	find({})

**Comment by SilverFire** [comment] 2016-02-24 13:14
> 2 12:04:38.386 18402.4 ms yii\mongodb\Query::count find.count(null)

And the same query is being executed immediately without Yii from the same machine?

**Comment by deplop** [comment] 2016-02-24 18:34
I have tried both in the console and by php extension \MongoDB\Client. They all return in no time.

**Comment by SilverFire** [comment] 2016-02-24 18:51
Can you try to debug the extension to find the thin place, because currently I have no idea where is the problem.
How to reproduce it? Is it enough to create 90k records in collection or not? Maybe it is stick to you environment.

**Comment by SilverFire** [comment] 2016-03-04 12:19
Reposted from https://github.com/yiisoft/yii2-mongodb/issues/56#issuecomment-191758354
Originally authored by @deplop 

____

@SilverFire 
I think I have figured out the problem. The problem is I was using PHP7 so I switched to hardsetting/yii2-mongodb for compatible with the new php mongodb driver, but I didn't remember that. This morning I installed mongofill for HHVM and switched back to yiisoft/yii2-mongodb and there is no longer bug. So I guess it's hardsetting's bug. I have reported it to him.

You can now close this. Thanks

**Closed by SilverFire** 2016-03-04 12:19 UTC
Labels: status:to be verified
